name: dbt_test

on:
  workflow_call:

jobs:
  dbt_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install 

      - name: Run specific dbt test to generate the test dbt project
        run: poetry run pytest test/auto_gen/test_e2e_batch_autogen.py::test_batch_model_generation_creates_project_structure -v

      - name: Install dbt
        run: pip install dbt-core

      - name: Run dbt commands
        working-directory: integration_tests/customer_repo/ecommerce_transaction_interactions_features_1
        run: |
          dbt clean
          dbt deps
          dbt run --full-refresh
          dbt run